# Generated by Django 4.0.5 on 2022-06-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Children',
            fields=[
                ('ChildId', models.AutoField(primary_key=True, serialize=False)),
                ('ParentId', models.IntegerField()),
                ('FirstName', models.CharField(max_length=500)),
                ('LastName', models.CharField(max_length=500)),
                ('ParentFirstName', models.CharField(max_length=500)),
                ('ParentLastName', models.CharField(max_length=500)),
                ('Age', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ChildrensWork',
            fields=[
                ('WorkId', models.AutoField(primary_key=True, serialize=False)),
                ('ChildId', models.IntegerField()),
                ('DocPath', models.CharField(max_length=500)),
                ('DateOfSubmission', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('EmployeeId', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=500)),
                ('LastName', models.CharField(max_length=500)),
                ('Street', models.CharField(max_length=500)),
                ('State', models.CharField(max_length=500)),
                ('City', models.CharField(max_length=500)),
                ('Zipcode', models.CharField(max_length=500)),
                ('Email', models.CharField(max_length=500)),
                ('PhoneNumber', models.CharField(max_length=500)),
                ('Password', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='EventRegisteration',
            fields=[
                ('RegisterationId', models.AutoField(primary_key=True, serialize=False)),
                ('ParentId', models.IntegerField()),
                ('EventId', models.IntegerField()),
                ('ParentsCountComing', models.IntegerField()),
                ('RegisterationDate', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('EventId', models.AutoField(primary_key=True, serialize=False)),
                ('EventsName', models.CharField(max_length=500)),
                ('EventDate', models.CharField(max_length=500)),
                ('EventTime', models.CharField(max_length=500)),
                ('EventsAddress', models.CharField(max_length=1000)),
                ('EventsCost', models.CharField(max_length=1000)),
                ('EventsSafety', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('ParentId', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=500)),
                ('LastName', models.CharField(max_length=500)),
                ('SpouseFirstName', models.CharField(max_length=500)),
                ('SpouseLastName', models.CharField(max_length=500)),
                ('Street', models.CharField(max_length=500)),
                ('State', models.CharField(max_length=500)),
                ('City', models.CharField(max_length=500)),
                ('Zipcode', models.CharField(max_length=500)),
                ('Email', models.CharField(max_length=500)),
                ('PhoneNumber', models.CharField(max_length=500)),
                ('Password', models.CharField(max_length=500)),
                ('NumberOfChildren', models.IntegerField()),
                ('BalanceDue', models.CharField(max_length=500)),
                ('DateOfJoining', models.CharField(max_length=500)),
                ('ApprovalStatus', models.BooleanField()),
            ],
        ),
    ]
