# Generated by Django 4.0.5 on 2022-06-08 21:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dayCareApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='EventsDescription',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
